### ISSUE TITLE
US 5 - Build ColorPalette component

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#12]
## Value proposition

As a user
I want to see a color palette with random colors, so I can get color suggestions

## Description

Color Palette

## Acceptance criteria

- [ ] a colorpalette with 5 random colors is visible

## Tasks

- [ ] write the component
- [ ] write an `axios.post` in the function `getRandomColors` to fetch the colors
- [ ] add a useState for that
- [ ] `map` over the state to display the fetched colors
- [ ] add a useEffect for `getRandomColors`
- [ ] basic styling
