### ISSUE TITLE
US 6 - Save and generate colors

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#13]
## Value proposition

As a User
I want to be able to save colors I like and get color suggestions based on these colors

## Description

Save and generate colors

## Acceptance criteria

- [ ] Save und delete each color
- [ ] generate color suggestions based on the saved colors

## Tasks

- [ ] add a useState for saved colors
- [ ] write an axios.post in `generateColors` with a dynamic requestbody to get color suggestions
- [ ] write a `toggleColorSave` function to manage the save-state of each color
- [ ] add a button for each color to `toggleColorSave` which displays "save" or "delete", based on the state
