### ISSUE TITLE
US 8 - Room Selection Page

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#18]
## Value proposition

As a user
I want to see a room selection Page where I can select the room I want to edit

## Description

Room Selection page

## Acceptance criteria

- [x] Page on path "/room-selection"
- [x] All rooms that are saved in the DB are visible
- [x] routing is working

## Tasks

- [x] branch "room-selection"
- [x] implement routing
- [x] write a component `room`
- [x] define the layout of single room
- [x] write component `rooms`
- [x] write an axios get request for `getAllColorRoomSets`
- [x] map the data-array and display all saved rooms
