### ISSUE TITLE
US 9 - CRUD for Rooms

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#20]
## Value proposition

As a developer
I want to be able to read, create, update and delete rooms

## Description

CRUD

## Acceptance criteria

- [x] Have a from to create a room
- [x] button with deletes a existing room
- [x] button to update room name

## Tasks

- [x] write component `CreateNewRoomForm` which creates a room
- [x] axios request on `saveNewColorRoomSet`
- [x] render the `CreateNewRoomForm` on the `RoomSelectionPage`

- [x] write a `handleDeleteClick` function in the `Room` component and create a delete button
- [x] axios request on `deleteColorRoomSetById`
- [x] render the deletebutton in the `Room` component

- [x] write a `handleUpdateRoomName` which updates the rooms name
- [x] write an `updateRoomName` backend method, write tests and 
- [x] axios request on `updateRoomName`
