### ISSUE TITLE
US 3 - Implement Sonarcloud

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#3]
## Value proposition

As a developer
I want to work with Sonarcloud to check for cleancode

## Description

Sonarcloud

## Acceptance criteria

- [ ] have Sonarcloud running for my project

## Tasks

- [ ]  Log in with Github at [sonarcloud.io](https://github.com/neuefische/ffm-java-23-2/blob/main/6-DevOps/03-Clean-Code-Sonarcloud/sonarcloud.io)
- [ ]  Analyze a New Project
- [ ]  Important for Fullstack Projects!
- [ ]  Select Setup A MonoRepo
- [ ]  Choose a Github Repository
- [ ]  Add a project for both Backend & Frontend and give them names.
- [ ]  Create a MonoRepo
- [ ]  Choose 'Previous version' as the basis for new code.
- [ ]  Create Projects
- [ ]  Configure the analysis for your Backend project.
- [ ]  Choose Github Actions as the analysis method
- [ ]  Save the SonarCloud Secret in your Github Repository.
- [ ]  Select Maven for Backend.
- [ ]  Enter the properties into your pom.xml.
- [ ]  Add the property <sonar.projectName>ProjectName</sonar.projectName> to your pom.xml.
- [ ]  Create a new Workflow file and copy the template from SonarCloud
- [ ]  Customize the name of the workflow.
- [ ]  Check the Java version.
- [ ]  Add the option --file backend/pom.xml to the run step (last line).
- [ ]  Add the Jacoco Dependency to your pom.xml.

```
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <version>0.8.10</version>
    <executions>
        <execution>
            <goals>
                <goal>prepare-agent</goal>
            </goals>
        </execution>
        <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
                <goal>report</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

- [ ] Configure the analysis for your frontend project.
- [ ] Choose Github Actions as the analysis method.
- [ ] Choose Other(for JS,TS,Go,Python,PHP,...) for the frontend.
- [ ] Create a new workflow file and copy the template from SonarCloud.
- [ ] Customize the name of the workflow.
- [ ] Create the sonar-project.properties file in the root directory of your project.
- [ ] Modify the line sonar.sources=./frontend/src and uncomment the line.
- [ ] Configure SonarCloud so that no tests are required for the frontend.
- [ ] Select Administration at the bottom left of the frontend project and then Quality Gate.
- [ ] Choose a Quality Gate that does not require tests or create a new one.
