### ISSUE TITLE
US 4 - set up branch protection

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#4]
## Value proposition

As a developer
I want to have my main branch protected so that I can ensure the integrity and quality of my code

## Description

Sonarcloud

## Acceptance criteria

- [ ] Push on main branch is impossible
- [ ] Coaches and bootcamp members are invited to be collaborators

## Tasks

- [ ] Set up branch protection
- [ ] Invite Coaches and bootcamp members as collaborators
