### ISSUE TITLE
US 1.7 - CD to cloud (Render)

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#7]
## Value proposition

As a developer
I want to use Render as a cloudservice so I can ensure that my app works the same in any environment

## Description

CD to Cloud (Render)

## Acceptance criteria

- [ ] CD to cloud works

## Tasks

  Set up Render:

- [ ] Register with Render
- [ ] Create a web service
- [ ] Select the option to deploy a Docker image
- [ ] Enter the name or URL of your Docker image on Dockerhub
- [ ] Choose a name for your web service
- [ ] Select the Free Tier!
- [ ] Create Web Service
- [ ] Enter the necessary environment variables in the Environment tab
