### ISSUE TITLE
US - RestController for getting the colors

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#8]
## Value proposition

As a developer
I want to have a restcontroller in which i write a postmapping, so I can get random colors from the API and I'm able to write other methods

## Description

Build Restcontroller

## Acceptance criteria

- [ ] have a randomColorController
- [ ] have a working Postmapping to get random colors from the API
- [ ] post request with postman via my controller is working

## Tasks

- [ ] create a randomColorController class
- [ ] write a postmapping including a webclient which interacts with the colormind API
- [ ] send a post request via postman
