### ISSUE TITLE
US - PostMapping for getting Colors

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/Color-up-Capstone#9]
## Value proposition

As a developer
I want to have a postmapping, so I can get random and colors and color suggestions from the API
## Description

Write Postmapping

## Acceptance criteria

- [ ] have a working Postmapping with an dynamic body to get colors from the API
- [ ] post request with postman via my controller is working

## Tasks

- [ ] write a postmapping including a webclient which interacts with the colormind API
- [ ] send a post request via postman
